import type { Metadata } from "next";
import { LegalPage } from "@/components/site/LegalPage";
import { BRAND } from "@/lib/site/brand";

export const metadata: Metadata = {
  title: `Terms · ${BRAND.name}`,
  description: "Plain terms for using the ReAround You beta.",
};

/** 使用条款（Beta）。只写现在成立的事，管辖法律等离开 Beta 时由运营主体补。 */
export default function TermsPage() {
  return (
    <LegalPage title="Terms of use" intro={`These are the terms for using ${BRAND.name} while it is in beta. They are short on purpose; if something is unclear, ask us.`}>
      <section>
        <h2>1. What the service is</h2>
        <p>
          {BRAND.name} shows places around a location and generates spoken and written stories about them using public sources and an AI language model. It is offered free of charge during the beta, in a browser and as an Android app that loads the same web app and needs an internet connection.
        </p>
      </section>

      <section>
        <h2>2. Beta means unfinished</h2>
        <ul>
          <li>Features may change, break or disappear without notice. Parts marked &ldquo;Coming soon&rdquo; do not work yet.</li>
          <li>Free resources are shared: when many people use the service at once you may be asked to wait.</li>
          <li>We may pause or end the beta at any time. Anything you saved is on your own device and stays there.</li>
        </ul>
      </section>

      <section>
        <h2>3. Stories can be wrong</h2>
        <p>
          The guide&rsquo;s stories are generated by an AI model from Wikipedia, Wikidata, Wikivoyage, OpenStreetMap and the UNESCO World Heritage List. They can contain mistakes, outdated facts and invented details. Check anything that matters, such as opening hours, prices, dates and names. The service is not a navigation, safety or emergency tool: routes are a suggested order of stops shown as straight lines, not turn-by-turn directions. Watch the road, respect local rules and private property.
        </p>
      </section>

      <section>
        <h2>4. Using the service</h2>
        <ul>
          <li>Use it for personal, non-commercial exploration.</li>
          <li>Do not try to overload the service, scrape it, bypass rate limits or use it to generate content that is unlawful, hateful or harassing.</li>
          <li>You are responsible for what you upload. Only take and send photos where you are allowed to.</li>
        </ul>
      </section>

      <section>
        <h2>5. Content and credit</h2>
        <p>
          Place descriptions come from sources under open licences (Wikipedia and Wikivoyage text: CC BY-SA; OpenStreetMap data: ODbL; map tiles © OpenStreetMap contributors). The generated stories are provided for your personal use. The {BRAND.name} name, the guide characters Mia and Milo, and the app&rsquo;s design belong to {BRAND.operator}.
        </p>
      </section>

      <section>
        <h2>6. No warranty, limited liability</h2>
        <p>
          The service is provided &ldquo;as is&rdquo; without warranties of any kind. To the extent permitted by law, {BRAND.operator} is not liable for losses arising from your use of the beta, including reliance on generated content. Nothing here limits rights that consumer law gives you and that cannot be waived.
        </p>
      </section>

      <section>
        <h2>7. Privacy</h2>
        <p>
          How data is handled is described in the <a href={BRAND.privacyPath}>Privacy page</a>, which is part of these terms.
        </p>
      </section>

      <section>
        <h2>8. Changes and contact</h2>
        <p>
          We may update these terms; the date at the top shows the current version. Governing law and venue will be stated here when the service leaves beta. Questions: <a href={`mailto:${BRAND.email}`}>{BRAND.email}</a>.
        </p>
      </section>
    </LegalPage>
  );
}
